version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: tenis-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sports_reservation
      MYSQL_USER: sports_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: